from tkinter import *
window = Tk()
spot1 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot1.grid(row=0, column=0)
spot2 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot2.grid(row=0, column=1)
spot3 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot3.grid(row=0, column=2)
spot4 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot4.grid(row=1, column=0)
spot5 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot5.grid(row=1, column=2)
spot6 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot6.grid(row=2, column=0)
spot7 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot7.grid(row=2, column=1)
spot8 =  Button(window, text = "opt", font=("Arial", 25), height=4, width=8)
spot8.grid(row=2, column=2)
window.mainloop()

